### ISSUE TITLE
Documentation on salting/masking mechanism? 

### ISSUE THREAD

**Issue by carn1x** [lpomfrey/django-debreach#16]
Could you please provide some basic documentation, or even just a link, to break down the process by which the masking/salting method operates at the conceptual level? Is your implementation replicating how Django >= 1.10 does it? Seems the django documentation and code commenting is very light on the explanation. In general googling CSRF Token masking/salting is proving to give me a lot of false positives. Thanks!

**Comment by lpomfrey** [comment]
At the most basic level, the goal is to ensure that the CSRF token displayed in the body of the request changes each time (the value in the cookie is always the same for every request, and this is fine). In order to do this we generate a random-string (or salt) and use this to scramble the value of the CSRF token in the response body in a reversible way. This is done by making the value in the response body contain both the salt and the result of scrambling the actual CSRF token. When that value is posted back we can extract the salt from it and then un-scramble the rest of the value to obtain the original CSRF token which is then checked against the value in the cookie.

django-debreach operates according to this section of the docs:

> This works by xor-ing the CSRF token when it is added to the template, so that {% csrf_token %} now produces a hidden field with a value that is `"<salt>$<actual-csrf-token-xor-ed-salt>"`. Then, when the form is POSTed, the middleware xors the CSRF token back into it's original form. This ensures that the CSRF content is never the same between requests. If you are passing the token using the `X-CSRFToken` header (e.g. using XHR) that header will also be processed in the same way.

The Django method is based on the same principle except they use a fixed length salt/random-string and no separator character like django-debreach. They also use a rotational cypher rather than an XOR based cypher (i.e. given a list of allowed characters they add the indexes of each character of the salt and the CSRF token to create the masked value and then subtract them again to unmask). But the end effect is basically the same.

**Comment by carn1x** [comment]
Ahh great, thanks for the clarification!

**Comment by lpomfrey** [comment]
No worries, glad it helped.
